# Generated by Django 4.1.1 on 2022-09-11 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_rollno',
            new_name='student_number',
        ),
    ]
